import {
	Instagram,
	Twitter,
	Facebook,
	ArrowRight,
	MapPin,
	Phone,
	Mail,
	ShoppingBag,
	Truck,
	Shield,
	Clock,
	Award,
	Search,
	User,
	ShoppingCart,
	Moon,
	Sun,
	Menu,
	ChevronDown,
} from "lucide-react";

export const icons = {
	iconoInstagram: Instagram,
	iconoTwitter: Twitter,
	iconoFacebook: Facebook,
	iconoFlechaDerecha: ArrowRight,
	iconoPuntoMapa: MapPin,
	iconoTelefono: Phone,
	iconoCorreo: Mail,
	iconoBolsaCompras: ShoppingBag,
	iconoCamion: Truck,
	iconoEscudo: Shield,
	iconoReloj: Clock,
	iconoCalidadPremium: Award,
	iconoBuscar: Search,
	iconoUsuario: User,
	iconoCarritoCompra: ShoppingCart,
	iconoLuna: Moon,
	iconoSol: Sun,
	iconoMenuHamburguesa: Menu,
	iconoDesplegarAbajo: ChevronDown,
};
